routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['before']], function () {
    Route::get('/', 'TopController@index')->name('top');

    Route::get('/privacy-policy', 'Privacy\PrivacyController@index')->name('privacy');
    Route::get('/about', 'About\AboutController@index')->name('about');
    Route::get('/release', 'About\AboutController@release')->name('release');
    Route::get('/administrator', 'About\AboutController@administrator')->name('administrator');
    Route::get('/contact', 'Contact\ContactController@index')->name('contact');
    Route::post('/contact', 'Contact\ContactController@send')->name('contact.send');
    Route::get('/search', 'Search\SearchController@index')->name('search');

    // 攻略


    // 記事
    Route::get('/article', 'Article\ArticleController@index')->name('article.index');
    Route::get('/article/category/{category_slug}', 'Article\ArticleController@categoryIndex')->name('article.category.index');
    Route::get('/article/example', 'Article\ArticleController@example')->name('article.example');
    Route::get('/article/{article_id}', 'Article\ArticleController@single')->name('article.single');


    // 後で消す
    Route::get('/vote_campaign', 'Vote\VoteController@index');
    Route::get('/vote_campaign/{vote_campaign_id}', 'Vote\VoteController@show');
    Route::get('/vote_campaign/{vote_campaign_id}/vote', 'Vote\VoteController@vote');

    // 投票
    Route::get('/vote-campaign', 'Vote\VoteController@index')->name('vote_campaign.index');
    Route::get('/vote-campaign/{vote_campaign_id}', 'Vote\VoteController@show')->name('vote_campaign.show');
    Route::get('/vote-campaign/{vote_campaign_id}/vote', 'Vote\VoteController@vote')->name('vote_campaign.vote');
    Route::post('/vote-campaign/{vote_campaign_id}/vote', 'Vote\VoteController@post')->name('vote_campaign.post');
    Route::get('/vote-campaign/{vote_campaign_id}/complete', 'Vote\VoteController@complete')->name('vote_campaign.complete');


    // その他のコンテンツ
    Route::get('/contents/timeline', 'Other\OtherController@timeline')->name('other.timeline');
    Route::get('/contents/game-title', 'Other\OtherController@gameTitle')->name('other.game_title');
    Route::get('/contents/real', 'Other\OtherController@real')->name('other.tactics');
    Route::get('/contents/war', 'Other\OtherController@war')->name('other.war');
    Route::get('/contents/war/{disturbance_id}', 'Other\OtherController@warSingle')->name('other.war.single');

    Route::get('/contents/vassals', 'Other\OtherController@vassals')->name('other.vassals');
    Route::get('/contents/diagnose', 'Other\DiagnoseController@index')->name('other.diagnose.index');
    Route::get('/contents/diagnose/new', 'Other\DiagnoseController@new')->name('other.diagnose.new');
    Route::post('/contents/diagnose/new', 'Other\DiagnoseController@create')->name('other.diagnose.create');
    Route::get('/contents/diagnose/complete/{diagnose_samurai_id}', 'Other\DiagnoseController@complete')->name('other.diagnose.complete');
    Route::get('/contents/word', 'Other\OtherController@word')->name('other.word');


    // 新信長
    Route::namespace('Shinnobunaga')->prefix('shinnobunaga')->name('shinnobunaga.')->group(function () {

        // 攻略
        Route::prefix('strategy')->name('strategy.')->group(function () {
            // 序盤の進め方
            Route::get('/beginner', 'StrategyController@beginner')->name('beginner');
            // クイズの答え
            // Route::get('/strategy/quiz', 'StrategyController@quiz')->name('strategy.quiz');
            // リセマラランキング
            Route::get('/resemara', 'StrategyController@resemara')->name('resemara');
            // 無課金向けキャラランキング
            Route::get('/mukakin', 'StrategyController@mukakin')->name('mukakin');
            // 家宝について
            Route::get('/heirloom', 'StrategyController@heirloom')->name('heirloom');
        });

        // データベース
        Route::prefix('database')->name('database.')->group(function () {

            // 最強ランキング
            Route::get('/samurai/ranking', 'DatabaseController@samuraiRanking')->name('samurais.ranking');

            // 武将名鑑
            Route::get('/samurai', 'DatabaseController@samuraiIndex')->name('samurais');
            Route::get('/samurai/rarity/{rarity}', 'DatabaseController@samuraiRarity')->name('samurais.show.rarity');
            Route::get('/samurai/appropriate-position/{appropriate_position}', 'DatabaseController@appropriatePosition')->name('samurais.show.appropriate_position');
            Route::get('/samurai/appropriate-army/{appropriate_army}', 'DatabaseController@appropriateArmy')->name('samurais.show.appropriate_army');
            Route::get('/samurai/{samurai_id}', 'DatabaseController@samuraiShow')->name('samurais.show');
        });

        // ガチャ
        Route::prefix('gacha')->name('gacha.')->group(function () {
            Route::get('/kokushimusou', 'GachaController@kokushimusou')->name('kokushimusou');
        });
    });

    // 覇道
    Route::namespace('Hadou')->prefix('hadou')->name('hadou.')->group(function () {
        // データベース
        Route::prefix('database')->name('database.')->group(function () {

            // 最強ランキング
            // Route::get('/samurai/ranking', 'DatabaseController@samuraiRanking')->name('samurais.ranking');

            // 武将名鑑
            Route::get('/samurai', 'HadouController@samuraiIndex')->name('samurais');
            Route::get('/samurai/{samurai_id}', 'HadouController@samuraiShow')->name('samurais.show');
            Route::get('/samurai/rarity/{rarity}', 'HadouController@samuraiRarity')->name('samurais.show.rarity');
            Route::get('/samurai/ranking/ability-score', 'HadouController@abilityScore')->name('database.ranking.ability_score');
        });
    });


    // 大志PK
    Route::namespace('TaishiPk')->prefix('taishi-pk')->group(function () {
        // 資源
        Route::get('/resource', 'ResourceController@index')->name('resource.index');
        // 設備
        Route::get('/facility', 'FacilityController@index')->name('facility.index');
        // 天守
        Route::get('/tensyu', 'TensyuController@index')->name('tensyu.index');
        // 施設
        Route::get('/building', 'BuildingController@index')->name('building.index');
        // 大命
        Route::get('/taimei', 'TaimeiController@index')->name('taimei.index');

        // 攻略
        // 軍事のコツ
        Route::get('/capture/military', 'CaptureController@military')->name('capture.military');
        // 行軍のコツ
        Route::get('/capture/march', 'CaptureController@march')->name('capture.march');
        // 決戦のコツ
        Route::get('/capture/decisive-battle', 'CaptureController@decisiveBattle')->name('capture.decisive_battle');
        // 攻城戦のコツ
        Route::get('/capture/siege', 'CaptureController@siege')->name('capture.siege');
        // 調略のコツ
        Route::get('/capture/plot', 'CaptureController@plot')->name('capture.plot');
        // 普請のコツ
        Route::get('/capture/general-contract', 'CaptureController@generalContract')->name('capture.general_contract');
        // 人事のコツ
        Route::get('/capture/human-resources', 'CaptureController@humanResources')->name('capture.human_resources');
        // 志について
        Route::get('/capture/will', 'CaptureController@will')->name('capture.will');
        // 内政のコツ
        Route::get('/capture/domestic-affairs', 'CaptureController@domesticAffairs')->name('capture.domestic_affairs');
        // 商業のコツ
        Route::get('/capture/commercial', 'CaptureController@commercial')->name('capture.commercial');
        // 農業のコツ
        Route::get('/capture/agriculture', 'CaptureController@agriculture')->name('capture.agriculture');
        // 外交のコツ
        Route::get('/capture/diplomacy', 'CaptureController@diplomacy')->name('capture.diplomacy');

        // 作戦
        Route::get('/strategy', 'StrategyController@index')->name('taishi-pk.strategy.index');

    });



    // 戦法
    Route::get('/{game_series_slug}/tactics', 'Tactics\TacticsController@index')->name('tactics.index');

    // シナリオ
    Route::get('/{game_series_slug}/scenario', 'Scenario\ScenarioController@index')->name('scenario.index');
    Route::get('/{game_series_slug}/scenario/recommend', 'Scenario\ScenarioController@recommend')->name('scenario.recommend');


    // 新生
    Route::namespace('Shinsei')->prefix('shinsei')->name('shinsei.')->group(function () {
        Route::get('/info', 'ShinseiController@info')->name('info');
        Route::get('/scenario', 'ShinseiController@scenario')->name('scenario');
        Route::get('/beginner', 'ShinseiController@beginner')->name('beginner');
        Route::get('/tensyou', 'ShinseiController@tensyou')->name('tensyou');
        Route::get('/policy', 'ShinseiController@policy')->name('policy');

        Route::get('/database/samurai/{samurai_id}', 'ShinseiController@show')->name('database.samurais.show');

        // Route::get('/fight', 'ShinseiController@fight')->name('fight');
        // Route::get('/domestic', 'ShinseiController@domestic')->name('domestic');
        // Route::get('/battle', 'ShinseiController@battle')->name('battle');
    });

    // 新生PK
    // Route::namespace('ShinseiPk')->prefix('shinsei-pk')->group(function () {

    Route::namespace('ShinseiPk')->prefix('shinsei-pk')->name('shinsei-pk.')->group(function () {
        Route::get('/database/samurai', 'ShinseiPkController@samuraiIndex')->name('database.samurais');
        Route::get('/database/samurai/{samurai_id}', 'ShinseiPkController@show')->name('database.show');
    });

    // データベース
    Route::get('/{game_series_slug}/database/samurai', 'Database\SamuraiController@index')->name('database.samurais');

app/Http/Controllers/Database/SamuraiController.php
<?php

namespace App\Http\Controllers\Database;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\GameTitle;
use App\Models\Samurai;
use App\Models\SamuraiParameter;
use App\Models\HadouSamuraiParameter;
use App\Models\ShinnobuSamuraiParameter;
use App\Models\TaishiStrategy;
use App\Models\TaishiPkHeirloomSamurai;
use App\Models\TaishiPkTactic;
use App\Models\SamuraiRelatedArticle;
use App\Models\ShinseiSamuraiParameter;
use App\Models\WarSamurai;

class SamuraiController extends Controller
{
    public function index(Request $request)
    {
        $GameTitle = GameTitle::slug($request->game_series_slug)->first();
        if (!isset($GameTitle)) {
            return redirect()->route('top');
        }

        $Samurais = Samurai::orderBy('furigana', 'asc')->get();

        if ($request->game_series_slug == 'taishi-pk') {
            $Samurais = Samurai::taishiPk()->orderBy('furigana', 'asc')->get();
        }
        if ($request->game_series_slug == 'shinsei') {
            $Samurais = Samurai::shinsei()->orderBy('furigana', 'asc')->get();
        }

        return view('database.samurais.index')->with([
            'Samurais' => $Samurais,
            'GameTitle' => $GameTitle,
          ]);
    }

    public function show(Request $request)
    {
        // 落ち着いたら削除
        if ($request->game_series_slug == 'taishi') {
            return redirect()->route('database.samurais.show', ['taishi-pk', $request->samurai_id]);
        }
        if ($request->game_series_slug == 'taishi_pk') {
            return redirect()->route('database.samurais.show', ['taishi-pk', $request->samurai_id]);
        }
        if ($request->game_series_slug == 'shinsei') {
            return redirect()->route('shinsei.database.samurais.show', [$request->samurai_id]);
        }
        $GameTitle = GameTitle::slug($request->game_series_slug)->first();
        $Samurai = Samurai::find($request->samurai_id);
        $SamuraiParameter = SamuraiParameter::gameTitleId($GameTitle->id)->samuraiId($Samurai->id)->first();
        $SamuraiPkTactics = TaishiPkTactic::get();

        $SamuraiRelatedArticles = SamuraiRelatedArticle::samuraiId($Samurai->id)->get();

        $Samurais = Samurai::taishiPk()->get();
        for ($i=1; $i < (count($Samurais) + 1) ; $i++) { 
            $NextSamurai = Samurai::taishiPk()->find($request->samurai_id + $i);

            if (isset($NextSamurai)) {
                break;
            }
        }
        for ($i=1; $i < (count($Samurais) + 1) ; $i++) { 
            $BeforeSamurai = Samurai::taishiPk()->find($request->samurai_id - $i);

            if (isset($BeforeSamurai)) {
                break;
            }
        }

        $TaishiPkHeirloomSamurais = TaishiPkHeirloomSamurai::samuraiId($request->samurai_id)->get();

        $imgCount = count(glob("img/samurai/min/" . $Samurai->id . "_" . "*.jpg"));

        $ShinnobuSamuraiParameter = ShinnobuSamuraiParameter::samuraiId($Samurai->id)->first();
        $ShinseiSamuraiParameter = Samurai::shinsei()->find($request->samurai_id);
        $HadouSamuraiParameter = HadouSamuraiParameter::samuraiId($Samurai->id)->first();
        $ShinseiPkSamuraiParameter = Samurai::shinseiPk()->find($Samurai->id);

        $WarSamurais = WarSamurai::samuraiId($Samurai->id)->get()->sortBy([
            ['war.start_year', true],
            ['war.start_month', true],
            ['war.start_day', true],
        ]);

        return view('database.samurais.samurai')->with([
            'BeforeSamurai' => $BeforeSamurai,
            'GameTitle' => $GameTitle,
            'imgCount' => $imgCount,
            'NextSamurai' => $NextSamurai,
            'Samurai' => $Samurai,
            'Samurais' => $Samurais,
            'SamuraiParameter' => $SamuraiParameter,
            'HadouSamuraiParameter' => $HadouSamuraiParameter,
            'ShinseiPkSamuraiParameter' => $ShinseiPkSamuraiParameter,
            'ShinnobuSamuraiParameter' => $ShinnobuSamuraiParameter,
            'ShinseiSamuraiParameter' => $ShinseiSamuraiParameter,
            'TaishiPkTactics' => $SamuraiPkTactics,
            'SamuraiRelatedArticles' => $SamuraiRelatedArticles,
            'TaishiPkHeirloomSamurais' => $TaishiPkHeirloomSamurais,
            'WarSamurais' => $WarSamurais,
        ]);
    }

    public function redirectShow(Request $request)
    {
        $GameTitle = GameTitle::slug(config('const.gameTitle'))->first();

        $shinseiSamurai = Samurai::shinsei()->find($request->samurai_id);
        $taishiPkSamurai = Samurai::taishiPk()->find($request->samurai_id);

        if (isset($shinseiSamurai)) {
            return redirect()->route('shinsei.database.samurais.show', [$request->samurai_id]);
        } elseif (isset($taishiPkSamurai)) {
            return redirect()->route('database.samurais.show', [$GameTitle->slug, $request->samurai_id]);
        } else {
            return redirect()->route('top');
        }
    }

    public function ranking(Request $request)
    {
        $GameTitle = GameTitle::slug($request->game_series_slug)->first();
        if ($GameTitle->slug == 'taishi-pk') {
            $SamuraiParameters = SamuraiParameter::with('samurai')->get();
        } elseif ($GameTitle->slug == 'shinsei') {
            $SamuraiParameters = ShinseiSamuraiParameter::with('samurai')->get();
        }
        // $SamuraiParameters = SamuraiParameter::with('samurai')->get();

        return view('database.samurais.ranking')->with([
            'GameTitle' => $GameTitle,
            'SamuraiParameters' => $SamuraiParameters,
          ]);
    }
}

app/Http/Controllers/Database/WillController.php
<?php

namespace App\Http\Controllers\Database;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\GameTitle;

class WillController extends Controller
{
    public function index(Request $request)
    {
        $GameTitle = GameTitle::slug($request->game_series_slug)->first();

        return view('database.will.index')->with([
            'GameTitle' => $GameTitle,
          ]);
    }
}

resources/views/shinnobunaga/database/samurai/appropriate_army.blade.php
@extends('layouts.layout')

@section('title', $appropriate_army_hiragana . 'キャラ一覧【新信長の野望】 | 信長の野望 徹底攻略')

@section('meta')
    <meta name="description" content="一覧です。レアリティ・属性を一覧で出しています！新信長の野望で武将を探す際の参考にしてください。">
    <meta property="og:description" content="一覧です。レアリティ・属性を一覧で出しています！新信長の野望で武将を探す際の参考にしてください。" />
    <meta property="og:title" content="{{ $appropriate_army_hiragana }}キャラ一覧【新信長の野望】 | 信長の野望 徹底攻略">
    <meta property="og:image" content="{{ Storage::disk('s3')->url('img/shinnobunaga/beginner/shinnobunaga.jpg') }}">
@endsection

@section('css')
@endsection

@section('js')
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": "{{ $appropriate_army_hiragana }}キャラ一覧【新信長の野望】| 信長の野望 徹底攻略",
            "url": "{{ url()->current() }}"
        }
    </script>
    <script type="text/javascript" src="{{ asset('js/table_of_contents.js') }}"></script>
@endsection

@section('content')
    <div class="inner inner_wrapper">
        <div class="single_contents">
            @include('components.game_aside')
            <div class="left_contents">
                <div class="article_contents">
                    <h1>
                        <div class="d-f ai-c">
                            <img src="{{ Storage::disk('s3')->url('img/shinnobunaga/samurai/' . $appropriate_army . '.png') }}" alt="" width="30px" height="30px" class="mr-8">
                            <p>{{ $appropriate_army_hiragana }}キャラ一覧【新信長の野望】</p>
                        </div>
                    </h1>
                    <div class="mt-24 article_body">
                        <p>【新信長の野望】の{{ $appropriate_army_hiragana }}のキャラ(武将)一覧です。レアリティ・属性を一覧で出しています！新信長の野望で武将を探す際の参考にしてください。</p>
                        <table class="font_small ta-c mt-24 w-100">
                            <tr>
                                <th style="width: 100px;">武将名</th>
                                <th>レアリティ</th>
                                <th>適正</th>
                                <th>統率</th>
                                <th>武勇</th>
                                <th>智略</th>
                                <th>政治</th>
                            </tr>

                            @foreach ($ShinnobuSamuraiParameters as $ShinnobuSamuraiParameter)
                                <tr>
                                    <td>
                                        <a href="{{ route('shinnobunaga.database.samurais.show', $ShinnobuSamuraiParameter->id) }}">
                                            <div>
                                                <img src="{{ Storage::disk('s3')->url('img/shinnobunaga/samurai/' . $ShinnobuSamuraiParameter->id . '.png') }}" style="margin: auto;" alt="" width="60px" height="100%">
                                            </div>
                                            @if (isset($ShinnobuSamuraiParameter->samurai))
                                                {{ $ShinnobuSamuraiParameter->samurai->name }}
                                            @endif
                                        </a>
                                    </td>
                                    <td>
                                        <img src="{{ Storage::disk('s3')->url('img/shinnobunaga/samurai/' . $ShinnobuSamuraiParameter->rarity . '.png') }}" style="margin: auto;" alt="" width="30px" height="100%" class="d-b">
                                    </td>
                                    <td>{{ $ShinnobuSamuraiParameter->appropriate_position }}</td>
                                    <td class="@if ($ShinnobuSamuraiParameter->leadership >= 600) back_orange @elseif ($ShinnobuSamuraiParameter->leadership >= 400) back_yellow @endif">{{ $ShinnobuSamuraiParameter->leadership }}</td>
                                    <td class="@if ($ShinnobuSamuraiParameter->brave >= 600) back_orange @elseif ($ShinnobuSamuraiParameter->brave >= 400) back_yellow @endif">{{ $ShinnobuSamuraiParameter->brave }}</td>
                                    <td class="@if ($ShinnobuSamuraiParameter->wisdom >= 600) back_orange @elseif ($ShinnobuSamuraiParameter->wisdom >= 400) back_yellow @endif">{{ $ShinnobuSamuraiParameter->wisdom }}</td>
                                    <td class="@if ($ShinnobuSamuraiParameter->affairs >= 600) back_orange @elseif ($ShinnobuSamuraiParameter->affairs >= 400) back_yellow @endif">{{ $ShinnobuSamuraiParameter->affairs }}</td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                    <div class="mt-36 pc_display">
                        <div id="im-f50b6c9400ee4f73ab4f9c133b3dfd74">
                            <script async src="https://imp-adedge.i-mobile.co.jp/script/v1/spot.js?20220104"></script>
                            <script>(window.adsbyimobile=window.adsbyimobile||[]).push({pid:76890,mid:546545,asid:1783181,type:"banner",display:"inline",elementid:"im-f50b6c9400ee4f73ab4f9c133b3dfd74"})</script>
                        </div>
                    </div>
                    <div class="mt-36 sp_display">
                        <div id="im-3c7e0a0de6cf4f969594b146872e3b60">
                            <script async src="https://imp-adedge.i-mobile.co.jp/script/v1/spot.js?20220104"></script>
                            <script>(window.adsbyimobile=window.adsbyimobile||[]).push({pid:76890,mid:546546,asid:1783183,type:"banner",display:"inline",elementid:"im-3c7e0a0de6cf4f969594b146872e3b60"})</script>
                        </div>
                    </div>
                    @include('components.recommend_articles')
                    @include('components.breadcrumbs', ['slug' => 'shinnobunaga.database.samurais.show.rarity', 'argument1' => $appropriate_army_hiragana ])
                </div>
            </div>
            @include('components.aside')
        </div>
    </div>
@endsection

resources/views/shinnobunaga/database/samurai/appropriate_position.blade.php
@extends('layouts.layout')

@section('title', $appropriate_position_hiragana . 'キャラ一覧【新信長の野望】 | 信長の野望 徹底攻略')

@section('meta')
    <meta name="description" content="一覧です。レアリティ・属性を一覧で出しています！新信長の野望で武将を探す際の参考にしてください。">
    <meta property="og:description" content="一覧です。レアリティ・属性を一覧で出しています！新信長の野望で武将を探す際の参考にしてください。" />
    <meta property="og:title" content="{{ $appropriate_position_hiragana }}キャラ一覧【新信長の野望】 | 信長の野望 徹底攻略">
    <meta property="og:image" content="{{ Storage::disk('s3')->url('img/shinnobunaga/beginner/shinnobunaga.jpg') }}">
@endsection

@section('css')
@endsection

@section('js')
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": "{{ $appropriate_position_hiragana }}キャラ一覧【新信長の野望】| 信長の野望 徹底攻略",
            "url": "{{ url()->current() }}"
        }
    </script>
    <script type="text/javascript" src="{{ asset('js/table_of_contents.js') }}"></script>
@endsection

@section('content')
    <div class="inner inner_wrapper">
        <div class="single_contents">
            @include('components.game_aside')
            <div class="left_contents">
                <div class="article_contents">
                    <h1>
                        <div class="d-f ai-c">
                            <img src="{{ Storage::disk('s3')->url('img/shinnobunaga/samurai/' . $appropriate_position . '.png') }}" alt="" width="40px" height="100%" class="mr-8">
                            <p>{{ $appropriate_position_hiragana }}キャラ一覧【新信長の野望】</p>
                        </div>
                    </h1>
                    <div class="mt-24 article_body">
                        <p>【新信長の野望】の{{ $appropriate_position_hiragana }}のキャラ(武将)一覧です。レアリティ・属性を一覧で出しています！新信長の野望で武将を探す際の参考にしてください。</p>
                        @if ($appropriate_position_hiragana == 'captain')
                            <p>武将の統率の高さによって部隊の兵数が増減するため、統率が高い武将を選択すると良い。</p>
                        @elseif ($appropriate_position_hiragana == 'pioneer')
                            <p>武将の武勇の高さによって部隊の攻撃力・防御力が増減するため、武勇が高い武将を選択すると良い。</p>
                        @elseif ($appropriate_position_hiragana == 'staff')
                            <p>武将の智略の高さによって部隊の攻撃力・防御力が増減するため、智略が高い武将を選択すると良い。</p>
                        @endif
                        <table class="font_small ta-c mt-24 w-100">
                            <tr>
                                <th style="width: 100px;">武将名</th>
                                <th>レアリティ</th>
                                <th>属性</th>
                                <th>統率</th>
                                <th>武勇</th>
                                <th>智略</th>
                                <th>政治</th>
                            </tr>

                            @foreach ($ShinnobuSamuraiParameters as $ShinnobuSamuraiParameter)
                                <tr>
                                    <td>
                                        <a href="{{ route('shinnobunaga.database.samurais.show', $ShinnobuSamuraiParameter->id) }}">
                                            <div>
                                                <img src="{{ Storage::disk('s3')->url('img/shinnobunaga/samurai/' . $ShinnobuSamuraiParameter->id . '.png') }}" style="margin: auto;" alt="" width="60px" height="100%">
                                            </div>
                                            @if (isset($ShinnobuSamuraiParameter->samurai))
                                                {{ $ShinnobuSamuraiParameter->samurai->name }}
                                            @endif
                                        </a>
                                    </td>
                                    <td>
                                        <img src="{{ Storage::disk('s3')->url('img/shinnobunaga/samurai/' . $ShinnobuSamuraiParameter->rarity . '.png') }}" style="margin: auto;" alt="" width="30px" height="100%" class="d-b">
                                    </td>
                                    <td>{{ $ShinnobuSamuraiParameter->appropriate_army }}</td>
                                    <td class="@if ($ShinnobuSamuraiParameter->leadership >= 600) back_orange @elseif ($ShinnobuSamuraiParameter->leadership >= 400) back_yellow @endif">{{ $ShinnobuSamuraiParameter->leadership }}</td>
                                    <td class="@if ($ShinnobuSamuraiParameter->brave >= 600) back_orange @elseif ($ShinnobuSamuraiParameter->brave >= 400) back_yellow @endif">{{ $ShinnobuSamuraiParameter->brave }}</td>
                                    <td class="@if ($ShinnobuSamuraiParameter->wisdom >= 600) back_orange @elseif ($ShinnobuSamuraiParameter->wisdom >= 400) back_yellow @endif">{{ $ShinnobuSamuraiParameter->wisdom }}</td>
                                    <td class="@if ($ShinnobuSamuraiParameter->affairs >= 600) back_orange @elseif ($ShinnobuSamuraiParameter->affairs >= 400) back_yellow @endif">{{ $ShinnobuSamuraiParameter->affairs }}</td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                    <div class="mt-36 pc_display">
                        <div id="im-f50b6c9400ee4f73ab4f9c133b3dfd74">
                            <script async src="https://imp-adedge.i-mobile.co.jp/script/v1/spot.js?20220104"></script>
                            <script>(window.adsbyimobile=window.adsbyimobile||[]).push({pid:76890,mid:546545,asid:1783181,type:"banner",display:"inline",elementid:"im-f50b6c9400ee4f73ab4f9c133b3dfd74"})</script>
                        </div>
                    </div>
                    <div class="mt-36 sp_display">
                        <div id="im-3c7e0a0de6cf4f969594b146872e3b60">
                            <script async src="https://imp-adedge.i-mobile.co.jp/script/v1/spot.js?20220104"></script>
                            <script>(window.adsbyimobile=window.adsbyimobile||[]).push({pid:76890,mid:546546,asid:1783183,type:"banner",display:"inline",elementid:"im-3c7e0a0de6cf4f969594b146872e3b60"})</script>
                        </div>
                    </div>
                    @include('components.recommend_articles')
                    @include('components.breadcrumbs', ['slug' => 'shinnobunaga.database.samurais.show.rarity', 'argument1' => $appropriate_position_hiragana ])
                </div>
            </div>
            @include('components.aside')
        </div>
    </div>
@endsection