routes/web.php
    Route::get('/about', 'About\AboutController@index')->name('about');
    Route::get('/release', 'About\AboutController@release')->name('release');
    Route::get('/administrator', 'About\AboutController@administrator')->name('administrator');
    Route::get('/contact', 'Contact\ContactController@index')->name('contact');
    Route::post('/contact', 'Contact\ContactController@send')->name('contact.send');
    Route::get('/search', 'Search\SearchController@index')->name('search');

    // 攻略


    // 記事
    Route::get('/article', 'Article\ArticleController@index')->name('article.index');
    Route::get('/article/category/{category_slug}', 'Article\ArticleController@categoryIndex')->name('article.category.index');
    Route::get('/article/example', 'Article\ArticleController@example')->name('article.example');
    Route::get('/article/{article_id}', 'Article\ArticleController@single')->name('article.single');


    // 後で消す
    Route::get('/vote_campaign', 'Vote\VoteController@index');
    Route::get('/vote_campaign/{vote_campaign_id}', 'Vote\VoteController@show');
    Route::get('/vote_campaign/{vote_campaign_id}/vote', 'Vote\VoteController@vote');

    // 投票
    Route::get('/vote-campaign', 'Vote\VoteController@index')->name('vote_campaign.index');
    Route::get('/vote-campaign/{vote_campaign_id}', 'Vote\VoteController@show')->name('vote_campaign.show');
    Route::get('/vote-campaign/{vote_campaign_id}/vote', 'Vote\VoteController@vote')->name('vote_campaign.vote');
    Route::post('/vote-campaign/{vote_campaign_id}/vote', 'Vote\VoteController@post')->name('vote_campaign.post');
    Route::get('/vote-campaign/{vote_campaign_id}/complete', 'Vote\VoteController@complete')->name('vote_campaign.complete');


    // その他のコンテンツ
    Route::get('/contents/timeline', 'Other\OtherController@timeline')->name('other.timeline');
    Route::get('/contents/game-title', 'Other\OtherController@gameTitle')->name('other.game_title');
    Route::get('/contents/real', 'Other\OtherController@real')->name('other.tactics');
    Route::get('/contents/war', 'Other\OtherController@war')->name('other.war');
    Route::get('/contents/war/{disturbance_id}', 'Other\OtherController@warSingle')->name('other.war.single');

    Route::get('/contents/vassals', 'Other\OtherController@vassals')->name('other.vassals');
    Route::get('/contents/diagnose', 'Other\DiagnoseController@index')->name('other.diagnose.index');
    Route::get('/contents/diagnose/new', 'Other\DiagnoseController@new')->name('other.diagnose.new');
    Route::post('/contents/diagnose/new', 'Other\DiagnoseController@create')->name('other.diagnose.create');
    Route::get('/contents/diagnose/complete/{diagnose_samurai_id}', 'Other\DiagnoseController@complete')->name('other.diagnose.complete');
    Route::get('/contents/word', 'Other\OtherController@word')->name('other.word');


    // 新信長
    Route::namespace('Shinnobunaga')->prefix('shinnobunaga')->name('shinnobunaga.')->group(function () {

        // 攻略
        Route::prefix('strategy')->name('strategy.')->group(function () {
            // 序盤の進め方
            Route::get('/beginner', 'StrategyController@beginner')->name('beginner');
            // クイズの答え
            // Route::get('/strategy/quiz', 'StrategyController@quiz')->name('strategy.quiz');
            // リセマラランキング
            Route::get('/resemara', 'StrategyController@resemara')->name('resemara');
            // 無課金向けキャラランキング
            Route::get('/mukakin', 'StrategyController@mukakin')->name('mukakin');
            // 家宝について
            Route::get('/heirloom', 'StrategyController@heirloom')->name('heirloom');
        });

        // データベース
        Route::prefix('database')->name('database.')->group(function () {

            // 最強ランキング
            Route::get('/samurai/ranking', 'DatabaseController@samuraiRanking')->name('samurais.ranking');

            // 武将名鑑
            Route::get('/samurai', 'DatabaseController@samuraiIndex')->name('samurais');
            Route::get('/samurai/rarity/{rarity}', 'DatabaseController@samuraiRarity')->name('samurais.show.rarity');
            Route::get('/samurai/appropriate-position/{appropriate_position}', 'DatabaseController@appropriatePosition')->name('samurais.show.appropriate_position');
            Route::get('/samurai/appropriate-army/{appropriate_army}', 'DatabaseController@appropriateArmy')->name('samurais.show.appropriate_army');
            Route::get('/samurai/{samurai_id}', 'DatabaseController@samuraiShow')->name('samurais.show');
        });

        // ガチャ
        Route::prefix('gacha')->name('gacha.')->group(function () {
            Route::get('/kokushimusou', 'GachaController@kokushimusou')->name('kokushimusou');
        });
    });

    // 覇道
    Route::namespace('Hadou')->prefix('hadou')->name('hadou.')->group(function () {
        // データベース
        Route::prefix('database')->name('database.')->group(function () {

            // 最強ランキング
            // Route::get('/samurai/ranking', 'DatabaseController@samuraiRanking')->name('samurais.ranking');

            // 武将名鑑
            Route::get('/samurai', 'HadouController@samuraiIndex')->name('samurais');
            Route::get('/samurai/{samurai_id}', 'HadouController@samuraiShow')->name('samurais.show');
            Route::get('/samurai/rarity/{rarity}', 'HadouController@samuraiRarity')->name('samurais.show.rarity');
            Route::get('/samurai/ranking/ability-score', 'HadouController@abilityScore')->name('database.ranking.ability_score');
        });
    });


    // 大志PK
    Route::namespace('TaishiPk')->prefix('taishi-pk')->group(function () {
        // 資源
        Route::get('/resource', 'ResourceController@index')->name('resource.index');
        // 設備
        Route::get('/facility', 'FacilityController@index')->name('facility.index');
        // 天守
        Route::get('/tensyu', 'TensyuController@index')->name('tensyu.index');
        // 施設
        Route::get('/building', 'BuildingController@index')->name('building.index');
        // 大命
        Route::get('/taimei', 'TaimeiController@index')->name('taimei.index');

        // 攻略
        // 軍事のコツ
        Route::get('/capture/military', 'CaptureController@military')->name('capture.military');
        // 行軍のコツ
        Route::get('/capture/march', 'CaptureController@march')->name('capture.march');
        // 決戦のコツ
        Route::get('/capture/decisive-battle', 'CaptureController@decisiveBattle')->name('capture.decisive_battle');
        // 攻城戦のコツ
        Route::get('/capture/siege', 'CaptureController@siege')->name('capture.siege');
        // 調略のコツ
        Route::get('/capture/plot', 'CaptureController@plot')->name('capture.plot');
        // 普請のコツ
        Route::get('/capture/general-contract', 'CaptureController@generalContract')->name('capture.general_contract');
        // 人事のコツ
        Route::get('/capture/human-resources', 'CaptureController@humanResources')->name('capture.human_resources');
        // 志について
        Route::get('/capture/will', 'CaptureController@will')->name('capture.will');
        // 内政のコツ
        Route::get('/capture/domestic-affairs', 'CaptureController@domesticAffairs')->name('capture.domestic_affairs');
        // 商業のコツ
        Route::get('/capture/commercial', 'CaptureController@commercial')->name('capture.commercial');
        // 農業のコツ
        Route::get('/capture/agriculture', 'CaptureController@agriculture')->name('capture.agriculture');
        // 外交のコツ
        Route::get('/capture/diplomacy', 'CaptureController@diplomacy')->name('capture.diplomacy');

        // 作戦
        Route::get('/strategy', 'StrategyController@index')->name('taishi-pk.strategy.index');

    });



    // 戦法
    Route::get('/{game_series_slug}/tactics', 'Tactics\TacticsController@index')->name('tactics.index');

    // シナリオ
    Route::get('/{game_series_slug}/scenario', 'Scenario\ScenarioController@index')->name('scenario.index');
    Route::get('/{game_series_slug}/scenario/recommend', 'Scenario\ScenarioController@recommend')->name('scenario.recommend');


    // 新生
    Route::namespace('Shinsei')->prefix('shinsei')->name('shinsei.')->group(function () {
        Route::get('/info', 'ShinseiController@info')->name('info');
        Route::get('/scenario', 'ShinseiController@scenario')->name('scenario');
        Route::get('/beginner', 'ShinseiController@beginner')->name('beginner');
        Route::get('/tensyou', 'ShinseiController@tensyou')->name('tensyou');
        Route::get('/policy', 'ShinseiController@policy')->name('policy');

        Route::get('/database/samurai/{samurai_id}', 'ShinseiController@show')->name('database.samurais.show');

        // Route::get('/fight', 'ShinseiController@fight')->name('fight');
        // Route::get('/domestic', 'ShinseiController@domestic')->name('domestic');
        // Route::get('/battle', 'ShinseiController@battle')->name('battle');
    });

    // 新生PK
    // Route::namespace('ShinseiPk')->prefix('shinsei-pk')->group(function () {

    Route::namespace('ShinseiPk')->prefix('shinsei-pk')->name('shinsei-pk.')->group(function () {
        Route::get('/database/samurai', 'ShinseiPkController@samuraiIndex')->name('database.samurais');
        Route::get('/database/samurai/{samurai_id}', 'ShinseiPkController@show')->name('database.show');
    });

    // データベース
    Route::get('/{game_series_slug}/database/samurai', 'Database\SamuraiController@index')->name('database.samurais');
    Route::get('/{game_series_slug}/database/samurai/{samurai_id}', 'Database\SamuraiController@show')->name('database.samurais.show');
    Route::get('/database/samurai/{samurai_id}', 'Database\SamuraiController@redirectShow')->name('database.samurais.redirect_show');
    Route::get('/{game_series_slug}/ranking/all', 'Database\SamuraiController@ranking')->name('database.ranking');

    Route::get('/{game_series_slug}/database/will', 'Database\WillController@index')->name('database.will');


    Route::get('sitemap.xml', 'SitemapController@sitemap')->name('sitemap');

app/Http/Controllers/ShinseiPk/ShinseiPkController.php
<?php

namespace App\Http\Controllers\ShinseiPk;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\GameTitle;
use App\Models\HadouSamuraiParameter;
use App\Models\Samurai;
use App\Models\SamuraiRelatedArticle;
use App\Models\ShinnobuSamuraiParameter;
use App\Models\ShinseiSamuraiParameter;
use App\Models\ShinseiPkSamuraiParameter;
use App\Models\ShinseiPkSkill;
use App\Models\WarSamurai;


class ShinseiPkController extends Controller
{
    public function samuraiIndex()
    {
        $ShinseiPkSamuraiParameters = ShinseiPkSamuraiParameter::with('samurai')->get();
        return view('shinsei-pk.samurai_index')->with([
            'ShinseiPkSamuraiParameters' => $ShinseiPkSamuraiParameters,
        ]);
    }

    public function show(Request $request)
    {
        $GameTitle = GameTitle::slug('shinsei-pk')->first();
        $ShinseiPkSamuraiParameter = ShinseiPkSamuraiParameter::with(['samurai'])->samuraiId($request->samurai_id)->first();

        $SamuraiRelatedArticles = SamuraiRelatedArticle::with(['article', 'article.articleCategorySearches', 'article.articleCategorySearches.articleCategory'])->samuraiId($ShinseiPkSamuraiParameter->samurai->id)->get();

        $NextSamurai = null;
        $BeforeSamurai = null;
        if ($ShinseiPkSamuraiParameter->id != 2216) {
            $NextSamurai = ShinseiPkSamuraiParameter::find($request->samurai_id + 1);
        }
        if ($ShinseiPkSamuraiParameter->id != 1) {
            $BeforeSamurai = ShinseiPkSamuraiParameter::find($request->samurai_id - 1);
        }

        // $imgCount = count(glob("img/shinsei/samurai/" . $Samurai->id . "_" . "*.jpg"));

        $ShinnobuSamuraiParameter = ShinnobuSamuraiParameter::samuraiId($request->samurai_id)->first();
        $TaishiPkSamuraiParameter = Samurai::taishiPk()->find($request->samurai_id);
        $HadouSamuraiParameter = HadouSamuraiParameter::samuraiId($request->samurai_id)->first();
        $ShinseiSamuraiParameter = ShinseiSamuraiParameter::samuraiId($request->samurai_id)->first();
        $WarSamurais = WarSamurai::with(['war', 'war.disturbance', 'samurai', 'war.warSamurais', 'war.warSamurais.samurai'])->samuraiId($request->samurai_id)->get()->sortBy([
            ['war.start_year', true],
            ['war.start_month', true],
            ['war.start_day', true],
        ]);

        $tactics = ShinseiPkSkill::tactics()->name($ShinseiPkSamuraiParameter->tactics)->first();
        $characteristic1 = ShinseiPkSkill::characteristic()->name($ShinseiPkSamuraiParameter->characteristic1)->first();
        $characteristic2 = ShinseiPkSkill::characteristic()->name($ShinseiPkSamuraiParameter->characteristic2)->first();
        $characteristic3 = ShinseiPkSkill::characteristic()->name($ShinseiPkSamuraiParameter->characteristic3)->first();
        $headOfHouse = ShinseiPkSkill::headOfHouse()->name($ShinseiPkSamuraiParameter->head_of_house)->first();
        $magistrate = ShinseiPkSkill::magistrate()->name($ShinseiPkSamuraiParameter->magistrate)->first();


        return view('shinsei-pk.samurai')->with([
            'BeforeSamurai' => $BeforeSamurai,
            'GameTitle' => $GameTitle,
            // 'imgCount' => $imgCount,
            'NextSamurai' => $NextSamurai,
            'ShinseiPkSamuraiParameter' => $ShinseiPkSamuraiParameter,
            // 'Samurais' => $Samurais,
            'HadouSamuraiParameter' => $HadouSamuraiParameter,
            'ShinseiSamuraiParameter' => $ShinseiSamuraiParameter,
            'ShinnobuSamuraiParameter' => $ShinnobuSamuraiParameter,
            'TaishiPkSamuraiParameter' => $TaishiPkSamuraiParameter,
            'SamuraiRelatedArticles' => $SamuraiRelatedArticles,
            'WarSamurais' => $WarSamurais,

            'tactics' => $tactics,
            'characteristic1' => $characteristic1,
            'characteristic2' => $characteristic2,
            'characteristic3' => $characteristic3,
            'headOfHouse' => $headOfHouse,
            'magistrate' => $magistrate,
        ]);
    }

}

resources/views/shinsei-pk/samurai_index.blade.php
@extends('layouts.layout')

@section('title', '武将名鑑【新生 PK】 | 信長の野望 徹底攻略')

@section('meta')
    <meta name="description" content="一覧です。レアリティ・属性を一覧で出しています！新生 PKで武将を探す際の参考にしてください。">
    <meta property="og:description" content="一覧です。レアリティ・能力値を一覧で出しています！新生 PKで武将を探す際の参考にしてください。" />
    <meta property="og:title" content="武将名鑑【新生 PK】 | 信長の野望 徹底攻略">
    <meta property="og:image" content="{{ asset('img/top/nobu.png') }}">
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('css/samurai.css') }}">
@endsection

@section('js')
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": "武将名鑑【新生 PK】| 信長の野望 徹底攻略",
            "url": "{{ url()->current() }}"
        }
    </script>
    <script type="text/javascript" src="{{ asset('js/samurai_kana.js') }}"></script>
@endsection

@section('content')
<div class="inner inner_wrapper">
    <div class="single_contents">
        @include('components.game_aside')
        <div class="left_contents">
            <article class="article_contents">
                <h1 id="title" class="h1 d-f ai-c">
                    <img src="{{ asset('img/common/samurai.png')}}" alt="武将名鑑アイコン" width="30px" height="30px" class="mr-8">
                    <p>武将名鑑【新生 PK】</p>
                </h1>
                <div class="mt-12">
                    <livewire:search />
                </div>
                {{-- <div class="mt-12">
                    <livewire:shinsei-pk-samurai />
                </div> --}}
                <div class="search_area back_white">
                    <div class="mt-12">
                        <ul class="d-f kana_ul">
                            <li class="kana_list">
                                <a href="" class="kana_anchor active">あ</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">か</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">さ</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">た</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">な</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">は</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">ま</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">や</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">ら</a>
                            </li>
                            <li class="kana_list">
                                <a href="" class="kana_anchor">わ</a>
                            </li>
                        </ul>
                    </div>
                    <div class="mt-12">
                        <ul class="shiin d-f">
                            <li class="shiin_li main" data-shiin="あ" data-boin-group="あ">
                                <a href="" class="shiin_anchor active">あ</a>
                            </li>
                            <li class="shiin_li main" data-shiin="い" data-boin-group="あ">
                                <a href="" class="shiin_anchor">い</a>
                            </li>
                            <li class="shiin_li main" data-shiin="う" data-boin-group="あ">
                                <a href="" class="shiin_anchor">う</a>
                            </li>
                            <li class="shiin_li main" data-shiin="え" data-boin-group="あ">
                                <a href="" class="shiin_anchor">え</a>
                            </li>
                            <li class="shiin_li main" data-shiin="お" data-boin-group="あ">
                                <a href="" class="shiin_anchor">お</a>
                            </li>
                            <li class="shiin_li" data-shiin="か" data-boin-group="か">
                                <a href="" class="shiin_anchor active">か</a>
                            </li>
                            <li class="shiin_li" data-shiin="き" data-boin-group="か">
                                <a href="" class="shiin_anchor">き</a>
                            </li>
                            <li class="shiin_li" data-shiin="く" data-boin-group="か">
                                <a href="" class="shiin_anchor">く</a>
                            </li>
                            <li class="shiin_li" data-shiin="け" data-boin-group="か">
                                <a href="" class="shiin_anchor">け</a>
                            </li>
                            <li class="shiin_li" data-shiin="こ" data-boin-group="か">
                                <a href="" class="shiin_anchor">こ</a>
                            </li>
                            <li class="shiin_li" data-shiin="さ" data-boin-group="さ">
                                <a href="" class="shiin_anchor active">さ</a>
                            </li>
                            <li class="shiin_li" data-shiin="し" data-boin-group="さ">
                                <a href="" class="shiin_anchor">し</a>
                            </li>
                            <li class="shiin_li" data-shiin="す" data-boin-group="さ">
                                <a href="" class="shiin_anchor">す</a>
                            </li>
                            <li class="shiin_li" data-shiin="せ" data-boin-group="さ">
                                <a href="" class="shiin_anchor">せ</a>
                            </li>
                            <li class="shiin_li" data-shiin="そ" data-boin-group="さ">
                                <a href="" class="shiin_anchor">そ</a>
                            </li>
                            <li class="shiin_li" data-shiin="た" data-boin-group="た">
                                <a href="" class="shiin_anchor active">た</a>
                            </li>
                            <li class="shiin_li" data-shiin="ち" data-boin-group="た">
                                <a href="" class="shiin_anchor">ち</a>
                            </li>
                            <li class="shiin_li" data-shiin="つ" data-boin-group="た">
                                <a href="" class="shiin_anchor">つ</a>
                            </li>
                            <li class="shiin_li" data-shiin="て" data-boin-group="た">
                                <a href="" class="shiin_anchor">て</a>
                            </li>
                            <li class="shiin_li" data-shiin="と" data-boin-group="た">
                                <a href="" class="shiin_anchor">と</a>
                            </li>
                            <li class="shiin_li" data-shiin="な" data-boin-group="な">
                                <a href="" class="shiin_anchor active">な</a>
                            </li>
                            <li class="shiin_li" data-shiin="に" data-boin-group="な">
                                <a href="" class="shiin_anchor">に</a>
                            </li>
                            <li class="shiin_li" data-shiin="ぬ" data-boin-group="な">
                                <a href="" class="shiin_anchor">ぬ</a>
                            </li>
                            <li class="shiin_li" data-shiin="ね" data-boin-group="な">
                                <a href="" class="shiin_anchor">ね</a>
                            </li>
                            <li class="shiin_li" data-shiin="の" data-boin-group="な">
                                <a href="" class="shiin_anchor">の</a>
                            </li>
                            <li class="shiin_li" data-shiin="は" data-boin-group="は">
                                <a href="" class="shiin_anchor active">は</a>
                            </li>
                            <li class="shiin_li" data-shiin="ひ" data-boin-group="は">
                                <a href="" class="shiin_anchor">ひ</a>
                            </li>
                            <li class="shiin_li" data-shiin="ふ" data-boin-group="は">
                                <a href="" class="shiin_anchor">ふ</a>
                            </li>
                            <li class="shiin_li" data-shiin="へ" data-boin-group="は">
                                <a href="" class="shiin_anchor">へ</a>
                            </li>
                            <li class="shiin_li" data-shiin="ほ" data-boin-group="は">
                                <a href="" class="shiin_anchor">ほ</a>
                            </li>
                            <li class="shiin_li" data-shiin="ま" data-boin-group="ま">
                                <a href="" class="shiin_anchor active">ま</a>
                            </li>
                            <li class="shiin_li" data-shiin="み" data-boin-group="ま">
                                <a href="" class="shiin_anchor">み</a>
                            </li>
                            <li class="shiin_li" data-shiin="む" data-boin-group="ま">
                                <a href="" class="shiin_anchor">む</a>
                            </li>
                            <li class="shiin_li" data-shiin="め" data-boin-group="ま">
                                <a href="" class="shiin_anchor">め</a>
                            </li>
                            <li class="shiin_li" data-shiin="も" data-boin-group="ま">
                                <a href="" class="shiin_anchor">も</a>
                            </li>
                            <li class="shiin_li" data-shiin="や" data-boin-group="や">
                                <a href="" class="shiin_anchor active">や</a>
                            </li>
                            <li class="shiin_li" data-shiin="ゆ" data-boin-group="や">
                                <a href="" class="shiin_anchor">ゆ</a>
                            </li>
                            <li class="shiin_li" data-shiin="よ" data-boin-group="や">
                                <a href="" class="shiin_anchor">よ</a>
                            </li>
                            <li class="shiin_li" data-shiin="ら" data-boin-group="ら">
                                <a href="" class="shiin_anchor active">ら</a>
                            </li>
                            <li class="shiin_li" data-shiin="り" data-boin-group="ら">
                                <a href="" class="shiin_anchor">り</a>
                            </li>
                            <li class="shiin_li" data-shiin="る" data-boin-group="ら">
                                <a href="" class="shiin_anchor">る</a>
                            </li>
                            <li class="shiin_li" data-shiin="れ" data-boin-group="ら">
                                <a href="" class="shiin_anchor">れ</a>
                            </li>
                            <li class="shiin_li" data-shiin="ろ" data-boin-group="ら">
                                <a href="" class="shiin_anchor">ろ</a>
                            </li>
                            <li class="shiin_li" data-shiin="わ" data-boin-group="わ">
                                <a href="" class="shiin_anchor active">わ</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <ul class="samurai_ul mt-24">
                    @foreach ($ShinseiPkSamuraiParameters as $ShinseiPkSamuraiParameter)
                        <li class="samurai_li @if(mb_substr($ShinseiPkSamuraiParameter->furigana, 0, 1) == 'あ') active @endif" data-kana="{{ mb_substr($ShinseiPkSamuraiParameter->furigana, 0, 1) }}">
                            <a href="{{ route('shinsei-pk.database.show', [$ShinseiPkSamuraiParameter->id]) }}" title="{{ $ShinseiPkSamuraiParameter->name }}" class="samurai_anchor">
                                <div class="img_area">
                                    <picture>
                                        <source type="image/webp" srcset="{{ My_func::return_min_samurai_img_webp_url($ShinseiPkSamuraiParameter->samurai->id, "shinsei-pk") }}">
                                        <img src="{{ My_func::return_min_samurai_img_url($ShinseiPkSamuraiParameter->samurai->id, "shinsei-pk") }}" alt="{{ $ShinseiPkSamuraiParameter->name }}のグラフィック画像" width="80%" height="100%" class="m-a samurai_img">
                                    </picture>
                                </div>
                                <div class="text_area">
                                    <p class="hover_white">{{ $ShinseiPkSamuraiParameter->name }} <span class="font_small hover_white">（{{ $ShinseiPkSamuraiParameter->furigana }}）</span></p>
                                    <p class="mt-8 font_small hover_white">{!! $ShinseiPkSamuraiParameter->samurai->retuden !!}</p>
                                </div>
                            </a>
                        </li>
                    @endforeach
                </ul>
            </article>
            @include('components.recommend_articles')
            @include('components.breadcrumbs', ['slug' => 'database.samurais', 'argument1' => $GameTitle])
        </div>
        @include('components.aside')
    </div>
</div>
@endsection